version: "3.2"
services:
    schmusic-api:
        container_name: schmusic-api
        build: 
            context: ./schmusic-api/
            dockerfile: Dockerfile.dev
        volumes:
            - ./schmusic-api/schmusic:/code
        command: python ./manage.py runserver 0.0.0.0:80
        expose:
            - "80"
        env_file: .env-api 
        stdin_open: true
        tty: true

    schmusic-studio:
        container_name: schmusic-studio
        build:
            context: ./schmusic-ui/
            dockerfile: Dockerfile.prod
        env_file: .env-ui
        volumes:
            - "./schmusic-ui/studio:/usr/src/app"
            - "/usr/src/app/node_modules"
        expose: 
            - "80"
        environment:
            - NODE_ENV=production

networks:
    default:
        external:
            name: webproxy
