version: "3.2"
services:
    schmusic-api:
        container_name: schmusic-api
        build: 
            context: ./schmusic-api/
            dockerfile: Dockerfile.dev
        volumes:
            - ./schmusic-api/schmusic:/code
        command: python ./manage.py runserver 0.0.0.0:80
        expose:
            - "80"
        env_file: .env-api 
        stdin_open: true
        tty: true

    schmusic-studio:
        container_name: schmusic-studio
        build:
            context: ./schmusic-ui/
            dockerfile: Dockerfile
        env_file: .env-ui
        volumes:
            - "./schmusic-ui/studio:/usr/src/app"
            - "/usr/src/app/node_modules"
        expose: 
            - "80"
        environment:
            - NODE_ENV=development
    #postgres:
    #container_name: postgres
    #restart: always
    #    image: postgres:9.3
    #    ports:
    #        - "5432:5432"
    #    volumes:
    #        - /var/lib/postgresql/data/


networks:
    default:
        external:
            name: webproxy
